config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  resources :users, only: [:index, :show, :new, :create, :edit, :update] do
    put '/change_password', to: 'users#change_password'
  end

  resources :sign_up_sheets do
    resources :attendees, only: [:index, :create, :destroy]
    get '/report', to: 'sign_up_sheets#report'
  end

  get '/verify_email/:token', to: 'users#verify_email'

  resource :sessions, only: [:create, :destroy]

  resources :events do
    resources :teams do
      resources :team_members, only: [:index, :new, :edit, :create, :update, :destroy]
    end
  end

  resources :announcements

  resources :accountability_logs do
    resources :submissions, only: [:index, :new, :show, :create, :destroy]
  end

  resources :documents

  namespace :admin do
    get 'dashboard'
    get 'teams'
    get 'attendance'
  end

  get 'courses', to: 'pages#courses'

  get 'log_in', to: 'sessions#new'
  get 'register', to: 'users#new'
  get 'log_out', to: 'sessions#destroy'
end

app/models/accountability_log.rb
# Accountability Log Model
class AccountabilityLog < ActiveRecord::Base
  validates :dueby, presence: true
  validates :closingdate, presence: true

  has_many :submissions
  has_many :users, through: :submissions
end

app/models/accountabilitylog.rb
class Accountabilitylog < ActiveRecord::Base

  validates :dueby, presence: true
  validates :closingdate, presence: true

  has_many :submissions
  has_many :users, through: :submissions
end

app/controllers/accountability_logs_controller.rb
# Accountability Log Controller, for submitting logs based on user
class AccountabilityLogsController < ApplicationController
  respond_to :html, :json

  add_breadcrumb 'Accountability Logs', :accountability_logs_path

  def index
    @accountability_logs = AccountabilityLog.all
    respond_with @accountability_logs
  end

  def show
    @accountability_log = AccountabilityLog.find_by(id: params[:id])
    if @accountability_log
      add_breadcrumb 'Accountability Log #' + @accountability_log.id.to_s, accountability_log_path(@accountability_log)
      add_breadcrumb 'Submissions', accountability_log_path(@accountability_log)
      respond_with @accountability_log
    else
      respond_to do |format|
        format.html { not_found }
        format.json { head status: :not_found }
      end
    end
  end

  def new
    @accountability_log = AccountabilityLog.new
    add_breadcrumb 'New Accountability Log', new_accountability_log_path
    respond_to :html
  end

  def edit
    @accountability_log = AccountabilityLog.find_by(id: params[:id])
    if @accountability_log
      add_breadcrumb 'Edit Accountability Log #' + @accountability_log.id.to_s, edit_accountability_log_path(@accountability_log)
      respond_with @accountability_log
    else
      respond_to do |format|
        format.html { not_found }
        format.json { head status: :not_found }
      end
    end
  end

  def create
    return head status: :forbidden if session[:user_id].nil?
    return head status: :forbidden unless User.find_by(id: session[:user_id]).admin?
    accountability_log = AccountabilityLog.new(accountability_log_parameters_create)
    if accountability_log.save
      head status: :created, location: accountability_log_path(accountability_log)
    else
      render json: {error: accountability_log.errors}, status: :bad_request
    end
  end

  def update
    accountability_log = AccountabilityLog.find_by(id: params[:id])
    return head status: :not_found unless accountability_log
    if session[:user_id].nil? || !User.find_by(id: session[:user_id]).admin?
      return head status: :forbidden
    end
    if accountability_log.update(accountability_log_parameters_update)
      head status: :ok
    else
      render json: {error: accountability_log.errors}, status: :bad_request
    end
  end

  def destroy
    accountability_log = AccountabilityLog.find_by(id: params[:id])
    return head status: :not_found unless accountability_log
    if session[:user_id].nil? || !User.find_by(id: session[:user_id]).admin?
      return head status: :forbidden
    end
    AccountabilityLog.destroy(accountability_log.id)
    head status: :ok
  end

  private

  def accountability_log_parameters_create
    params.require(:accountability_log).permit(:dueby, :closingdate)
  end

  def accountability_log_parameters_update
    params.require(:accountability_log).permit(:dueby, :closingdate)
  end
end

app/helpers/accountability_logs_helper.rb
# Helpers for Accountability Log
module AccountabilityLogsHelper
end

app/views/accountability_logs/_accountability_log.html.erb
<tr>
  <td class='log_posted'><%= format_date accountability_log.created_at %></td>
  <td class='log_dueby'><%= format_date accountability_log.dueby %></td>
  <td class='log_closing'><%= format_date accountability_log.closingdate %></td>
  <% submission = Submission.find_by_accountability_log_id_and_user_id(accountability_log.id, session[:user_id]) %>
  <% if submission.nil? %>
    <td class='log_create'><%= link_to 'Create Submission', new_accountability_log_submission_path(accountability_log.id), class: 'btn btn-info' %></td>
  <% else %>
    <td class='log_create'><%= link_to 'View Submission', accountability_log_submission_path(accountability_log.id, submission.id), class: 'btn btn-primary' %></td>
  <% end %>
  <% if current_user.is_admin %>
    <td class='log_view'><%= link_to 'View', accountability_log_path(accountability_log.id), class: 'btn btn-primary' %></td>
  <% end %>
</tr>

app/views/accountability_logs/_submission.html.erb
<%
submission = Submission.find_by_accountability_log_id_and_user_id(params[:id], user.id)
%>
<% if !submission.nil? %>
  <tr>
<% else %>
  <tr class='text-muted'>
<% end %>
  <% if !submission.nil? %>
    <td class='submission_name'><%= user.name %></td>
    <td class='submission_timestamp'><%= format_time submission.created_at %></td>
    <td class='submission_view'><%= link_to 'View Submission', accountability_log_submission_path(submission.accountability_log, submission.id), class: 'btn btn-primary btn-sm' %></td>
  <% else %>
    <td class='submission_name'><%= user.name %> <i class="fa fa-clock-o" aria-hidden="true"></i></td>
    <td></td>
    <td></td>
  <% end %>
  <td class='submission_view_user'><%= link_to 'View User', user_path(user.id), class: 'btn btn-secondary btn-sm' %></td>
</tr>

app/views/accountability_logs/edit.html.erb
<div class="main-div">
  <h1>Edit Accountability Log <%= format_time @accountability_log.dueby%></h1>

  <%= form_for @accountability_log, remote: true do |f| %>
    <fieldset class="form-group">
      <%= f.label :dueby, class: 'form-control-label' %>
      <%= f.date_select :dueby %>
    </fieldset>

    <fieldset class="form-group">
      <%= f.label :closingdate, class: 'form-control-label' %>
      <%= f.date_select :closingdate %>
    </fieldset>

    <%= f.submit 'Update', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/accountability_logs/index.html.erb
<div class="main-div">
  <% if logged_in %>
    <% if User.find_by_id(session[:user_id]).admin? %>
      <%= link_to new_accountability_log_path, class: 'btn btn-info pull-xs-right' do %>
        <i class="fa fa-plus"></i> Create a New Accountability Log
      <% end %>
    <% end %>
  <% end %>
  <h1>Accountability Logs</h1>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Posted</th>
        <th>Due By</th>
        <th>Final Closing Date</th>
        <th></th>
        <% if current_user.is_admin %>
          <th></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <%= render @accountability_logs or 'No accountability logs have been posted.' %>
    </tbody>
  </table>
</div>

app/views/accountability_logs/new.html.erb
<div class="main-div">
  <h1>Create a New Accountability Log</h1>

  <%= form_for @accountability_log, remote: true do |f| %>
    <fieldset class="form-group">
      <%= f.label :dueby, class: 'form-control-label' %>
      <%= f.date_select :dueby %>
    </fieldset>

    <fieldset class="form-group">
      <%= f.label :closingdate, class: 'form-control-label' %>
      <%= f.date_select :closingdate %>
    </fieldset>

    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/accountability_logs/show.html.erb
<div class='main-div'>
  <h1><%= format_date @accountability_log.dueby %><br>
  <small class='text-muted'>posted <%= format_time @accountability_log.created_at %></small></h1>
  <% if logged_in && current_user.is_admin %>
    <%= link_to 'Edit Accountability Log', edit_accountability_log_path(@accountability_log), class: 'btn btn-warning btn-sm btn-block' %>
  <% end %>
  <hr>
  <h2>Submissions</h2>
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th>User</th>
        <th>Created At Timestamp</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: 'submission', collection: User.where("rank < ? AND rank > ?", 8, 0), as: :user or 'No submissions have been posted for this accountability log.'%>
    </tbody>
  </table>
</div>