config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  resources :users, only: [:index, :show, :new, :create, :edit, :update] do
    put '/change_password', to: 'users#change_password'
  end

  resources :sign_up_sheets do
    resources :attendees, only: [:index, :create, :destroy]
    get '/report', to: 'sign_up_sheets#report'
  end

  get '/verify_email/:token', to: 'users#verify_email'

  resource :sessions, only: [:create, :destroy]

  resources :events do
    resources :teams do
      resources :team_members, only: [:index, :new, :edit, :create, :update, :destroy]
    end
  end

  resources :announcements

  resources :accountability_logs do
    resources :submissions, only: [:index, :new, :show, :create, :destroy]
  end

  resources :documents

  namespace :admin do
    get 'dashboard'
    get 'teams'
    get 'attendance'
  end

  get 'courses', to: 'pages#courses'

  get 'log_in', to: 'sessions#new'
  get 'register', to: 'users#new'
  get 'log_out', to: 'sessions#destroy'
end

app/models/sign_up_sheet.rb
# Sign Up Sheet for Meetings
class SignUpSheet < ActiveRecord::Base
  validates :name, presence: true
  validates :name, length: {maximum: 128}

  validates :date, presence: true

  has_many :attendees
  has_many :users, through: :attendees
end

app/controllers/sign_up_sheets_controller.rb
# Controller for Sign Up Sheets
class SignUpSheetsController < ApplicationController
  respond_to :html, :json

  add_breadcrumb 'Sign Up Sheets', :sign_up_sheets_path

  def index
    @sign_up_sheets = SignUpSheet.all
    respond_with @sign_up_sheets
  end

  def show
    @sign_up_sheet = SignUpSheet.find_by(id: params[:id])
    if @sign_up_sheet
      add_breadcrumb @sign_up_sheet.name, sign_up_sheet_path(@sign_up_sheet)
      respond_with @sign_up_sheet
    else
      respond_to do |format|
        format.html { not_found }
        format.json { head status: :not_found }
      end
    end
  end

  def new
    @sign_up_sheet = SignUpSheet.new
    add_breadcrumb 'New Sign Up Sheet', new_sign_up_sheet_path
    respond_to :html
  end

  def edit
    @sign_up_sheet = SignUpSheet.find_by(id: params[:id])
    if @sign_up_sheet
      add_breadcrumb 'Edit ' + @sign_up_sheet.name, edit_sign_up_sheet_path(@sign_up_sheet)
      respond_with @sign_up_sheet
    else
      respond_to do |format|
        format.html { not_found }
        format.json { head status: :not_found }
      end
    end
  end

  def report
    @sign_up_sheet = SignUpSheet.find_by(id: params[:sign_up_sheet_id])
    if @sign_up_sheet
      respond_with @sign_up_sheet
    else
      respond_to do |format|
        format.html { not_found }
        format.json { head status: :not_found }
      end
    end
  end

  def create
    return head status: :forbidden if session[:user_id].nil?
    return head status: :forbidden unless User.find_by(id: session[:user_id]).admin?

    sign_up_sheet = SignUpSheet.new(sign_up_sheet_parameters_create)
    if sign_up_sheet.save
      head status: :created, location: sign_up_sheet_path(sign_up_sheet)
    else
      render json: {error: sign_up_sheet.errors}, status: :bad_request
    end
  end

  def update
    sign_up_sheet = SignUpSheet.find_by(id: params[:id])
    return head status: :not_found unless sign_up_sheet

    if session[:user_id].nil? || !User.find_by(id: session[:user_id]).admin?
      return head status: :forbidden
    end
    if sign_up_sheet.update(sign_up_sheet_parameters_update)
      head status: :ok
    else
      render json: {error: sign_up_sheet.errors}, status: :bad_request
    end
  end

  def destroy
    sign_up_sheet = SignUpSheet.find_by(id: params[:id])
    return head status: :not_found unless sign_up_sheet

    if session[:user_id].nil? || !User.find_by(id: session[:user_id]).admin?
      return head status: :forbidden
    end
    sign_up_sheet.destroy
    head status: :ok
  end

  private

  def sign_up_sheet_parameters_create
    params.require(:sign_up_sheet).permit(:name, :date)
  end

  def sign_up_sheet_parameters_update
    params.require(:sign_up_sheet).permit(:name, :date)
  end
end

app/helpers/sign_up_sheets_helper.rb
# Helpers for Sign Up Sheets
module SignUpSheetsHelper
end

app/views/sign_up_sheets/_attendee.html.erb
<tr>
  <td class='attendee_name'><%= attendee.user.name %></td>
  <td class='attendee_view'><%= link_to 'View', user_path(attendee.user.id), class: 'btn btn-primary' %></td>
</tr>

app/views/sign_up_sheets/_attendee_report.html.erb
<tr>
  <td class='attendee_name'><%= attendee.user.name %></td>
</tr>

app/views/sign_up_sheets/_sign_up_sheet.html.erb
<tr>
  <td class='sheet_name'><%= sign_up_sheet.name %></td>
  <td class='sheet_time'><%= format_date sign_up_sheet.date %> EST</td>
  <td class='sheet_view'><%= link_to 'View', sign_up_sheet_path(sign_up_sheet.id), class: 'btn btn-primary' %></td>
</tr>

app/views/sign_up_sheets/edit.html.erb
<div class="main-div">
  <h1>Edit <%= @sign_up_sheet.name %></h1>

  <%= form_for @sign_up_sheet, remote: true do |f| %>
    <fieldset class="form-group">
      <%= f.label :name, class: 'form-control-label' %>
      <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
    </fieldset>

    <fieldset class="form-group">
      <%= f.label :date, class: 'form-control-label' %>
      <%= f.date_select :date %>
    </fieldset>

    <%= f.submit 'Update', class: 'btn btn-primary' %>
  <% end %>
  <hr>
  <%= button_to 'Remove Sign Up Sheet', { action: 'destroy', id: @sign_up_sheet.id }, method: :delete, form_class: 'remove_sheet', remote: true, class: 'btn btn-danger', data: { confirm: "Are you sure?" } %>
</div>

app/views/sign_up_sheets/index.html.erb
<div class="main-div">
  <% if logged_in %>
    <% if User.find_by_id(session[:user_id]).admin? %>
      <%= link_to new_sign_up_sheet_path, class: 'btn btn-info pull-xs-right' do %>
        <i class="fa fa-plus"></i> Create a New Sign Up Sheet
      <% end %>
    <% end %>
  <% end %>
  <h1>All Sign Up Sheets</h1>
  <table class="table table-striped">
    <tbody>
      <%= render @sign_up_sheets %>
    </tbody>
  </table>
</div>

app/views/sign_up_sheets/new.html.erb
<div class="main-div">
  <h1>Create a New Sign Up Sheet</h1>

  <%= form_for @sign_up_sheet, remote: true do |f| %>
    <fieldset class="form-group">
      <%= f.label :name, class: 'form-control-label' %>
      <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
    </fieldset>

    <fieldset class="form-group">
      <%= f.label :date, class: 'form-control-label' %>
      <%= f.date_select :date %>
    </fieldset>

    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/sign_up_sheets/report.html.erb
<div class='main-div'>

  <h1 class="display-3"><%= @sign_up_sheet.name %></h1>
  <p class="lead"><%= format_date @sign_up_sheet.date %></p>
  <h2>Attendees</h2>
  <h2><small class="text-muted">Attendee Count: <%= @sign_up_sheet.attendees.count %></small></h2>
  <table class="table table-striped table-bordered table-sm">
    <tbody>
      <%= render partial: 'attendee_report', collection: @sign_up_sheet.attendees, as: :attendee or 'No attendees have signed up.'%>
    </tbody>
  </table>
</div>

app/views/sign_up_sheets/show.html.erb
<div class='main-div'>
  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-3"><%= @sign_up_sheet.name %></h1>
      <p class="lead"><%= format_date @sign_up_sheet.date %></p>
      <hr class="m-y-2">
      <p class="lead">
        <%= link_to 'View Check In Page', sign_up_sheet_attendees_path(@sign_up_sheet.id), class: 'btn btn-primary btn-lg' %>
        <% if logged_in && User.find_by_id(session[:user_id]).admin? %>
          <%= link_to 'Report Attendees', sign_up_sheet_report_path(@sign_up_sheet.id), class: 'btn btn-secondary btn-lg' %>
          <%= link_to 'Edit Sheet', edit_sign_up_sheet_path(@sign_up_sheet.id), class: 'btn btn-warning btn-lg' %>
        <% end %>
      </p>
    </div>
  </div>
  <h2>Attendees</h2>
  <table class="table table-striped">
    <tbody>
      <%= render partial: 'attendee', collection: @sign_up_sheet.attendees, as: :attendee or 'No attendees have signed up.'%>
    </tbody>
  </table>
</div>