config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  resources :users, only: [:index, :show, :new, :create, :edit, :update] do
    put '/change_password', to: 'users#change_password'
  end

  resources :sign_up_sheets do
    resources :attendees, only: [:index, :create, :destroy]
    get '/report', to: 'sign_up_sheets#report'
  end

  get '/verify_email/:token', to: 'users#verify_email'

  resource :sessions, only: [:create, :destroy]

  resources :events do
    resources :teams do
      resources :team_members, only: [:index, :new, :edit, :create, :update, :destroy]
    end
  end

  resources :announcements

  resources :accountability_logs do
    resources :submissions, only: [:index, :new, :show, :create, :destroy]
  end

  resources :documents

  namespace :admin do
    get 'dashboard'
    get 'teams'
    get 'attendance'
  end

  get 'courses', to: 'pages#courses'

  get 'log_in', to: 'sessions#new'
  get 'register', to: 'users#new'
  get 'log_out', to: 'sessions#destroy'
end

app/models/accountability_log.rb
# Accountability Log Model
class AccountabilityLog < ActiveRecord::Base
  validates :dueby, presence: true
  validates :closingdate, presence: true

  has_many :submissions
  has_many :users, through: :submissions
end

app/models/accountabilitylog.rb
class Accountabilitylog < ActiveRecord::Base

  validates :dueby, presence: true
  validates :closingdate, presence: true

  has_many :submissions
  has_many :users, through: :submissions
end

app/models/announcement.rb
# Announcement for site wide posting
class Announcement < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true
  validates :title, length: {maximum: 64}
  validates :body, presence: true
  validates :body, length: {maximum: 5120}
  validates :user, presence: true
end

app/models/attendee.rb
# Attendees for Sign Up Sheets
class Attendee < ActiveRecord::Base
  belongs_to :user
  belongs_to :sign_up_sheet

  validates :user, presence: true
  validates :sign_up_sheet, presence: true
  validates :user, uniqueness: {scope: :sign_up_sheet}
end

app/models/document.rb
# Site wide documents
class Document < ActiveRecord::Base
  validates :title, presence: true
  validates :title, length: {maximum: 64}

  validates :link, presence: true
  validates :link, length: {maximum: 64}
end

app/models/event.rb
# Model that represents a TSA event
class Event < ActiveRecord::Base
  validates :name, presence: true
  validates :name, length: {minimum: 1, maximum: 64}
  validates :description, presence: true
  validates :description, length: {maximum: 1024}
  validates :max_members_per_team, presence: true
  validates :max_members_per_team, numericality: {greater_than: 0}

  has_many :teams
end

app/models/sign_up_sheet.rb
# Sign Up Sheet for Meetings
class SignUpSheet < ActiveRecord::Base
  validates :name, presence: true
  validates :name, length: {maximum: 128}

  validates :date, presence: true

  has_many :attendees
  has_many :users, through: :attendees
end

app/models/submission.rb
# Submission of an Accountability Log
class Submission < ActiveRecord::Base
  belongs_to :accountability_log
  belongs_to :user

  validates :binderstatus, presence: true
  validates :binderstatus, length: {maximum: 2048}
  validates :tasks, presence: true
  validates :tasks, length: {maximum: 2048}
  validates :goals, presence: true
  validates :goals, length: {maximum: 2048}

  validates :user, presence: true
  validates :accountability_log, presence: true
end

app/models/team.rb
# A team for a certain event
class Team < ActiveRecord::Base
  belongs_to :event

  validates :name, presence: true
  validates :name, length: {minimum: 1, maximum: 64}
  validates :event, presence: true

  validates :closed, inclusion: [true, false]

  has_many :team_members
  has_many :users, through: :team_members

  def full
    team_members.count >= event.max_members_per_team
  end
end

app/models/team_member.rb
# A member of a specific team for a certain event
class TeamMember < ActiveRecord::Base
  belongs_to :user
  belongs_to :team

  validates :user, presence: true
  validates :team, presence: true
  validates :user, uniqueness: {scope: :team}

  validates :admin, inclusion: [true, false]

  def admin?
    admin
  end
end

app/models/user.rb
# = User
# Represents a user on the website
#
# == Data
# [name]  String that contains the user's real name.
# [email] String that contains the user's email, used to send the verification email.
# [password_digest] Pair of strings that contains the user's password.
# [verified] Boolean that contains if the user has been verified by email.
# [verify_token] String that contains the verification token that is send by email to verify the user
# [rank] Integer that defines the user's site rank
# === Ranks
# [0] Unpaid Member
# [1] Member
# [2] Sergeant-at-Arms
# [3] Reporter
# [4] Treasurer
# [5] Secretary
# [6] Vice President
# [7] President
# [8] Advisor
# == Attributes
# * Adds a token before creation.
# * Must have a secure password (At least 8 characters long and be present)
# * Name must be present
# * Email must be present, must be formatted properly, and must be unique
# * Verified must be either true or false
class User < ActiveRecord::Base
  before_create :add_token

  has_secure_password
  validates :name, presence: true
  validates :email, presence: true
  validates_email_format_of :email
  validates :email, uniqueness: true
  validates :password, length: {minimum: 8}, on: :create
  validates :verified, inclusion: [true, false]
  validates :disabled, inclusion: [true, false]

  validates :rank, presence: true

  has_many :attendees

  # Renders a user as json with the password_digest excluded.
  def as_json(options = {})
    options[:except] ||= [:password_digest]
    super(options)
  end

  # Returns whether the user has paid their fees and thus if they are offically considered a member.
  def member?
    rank > 0
  end

  # Returns if the user is an admin or not.
  def admin?
    rank > 1
  end

  def officer?
    rank > 1 && rank <= 6
  end

  # Returns if the user is an advisor or not.
  def advisor?
    rank >= 7
  end

  def rank_title
    titles = ['Guest', 'Member', 'Sergeant-at-Arms', 'Reporter', 'Treasurer', 'Secretary', 'Vice President', 'President', 'Advisor']
    titles[rank]
  end

  private

  def add_token
    self.verify_token = SecureRandom.uuid if verify_token.blank?
  end
end

app/helpers/admin_helper.rb
# Helpers for Admin Dashboard
module AdminHelper
end

app/helpers/application_helper.rb
# Helper functions for use across Application
module ApplicationHelper
  def logged_in
    session[:user_id] && User.find_by(id: session[:user_id])
  end

  def current_user
    session[:user_id] && User.find_by(id: session[:user_id])
  end

  def format_date(date)
    date.to_formatted_s(:long)
  end

  def report_action_exist?
    begin
      current_page?(action: 'report')
    rescue
      return false
    end

    true
  end

  def markdown
    Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true)
  end

  def format_time(time)
    time.strftime('%b %d, %Y %I:%M %p')
  end

  def rank_title(rank)
    titles = ['Guest', 'Member', 'Sergeant-at-Arms', 'Reporter', 'Treasurer', 'Secretary', 'Vice President', 'President', 'Advisor']
    titles[rank]
  end

  def current_user_submission_count
    session[:user_id] && Submission.where(user_id: session[:user_id]).count
  end

  def current_user_submission_todo
    session[:user_id] && (AccountabilityLog.count - Submission.where(user_id: session[:user_id]).count)
  end
end

app/helpers/attendees_helper.rb
# Helper for Attendees
module AttendeesHelper
end

app/helpers/documents_helper.rb
# Helpers for Documents
module DocumentsHelper
end

app/helpers/events_helper.rb
# Helper for Events
module EventsHelper
end

app/helpers/pages_helper.rb
# Functions for Pages
module PagesHelper
end

app/helpers/sessions_helper.rb
# Functions for Session
module SessionsHelper
end

app/helpers/teams_helper.rb
# Helpers for Team Views and Controller
module TeamsHelper
end

app/helpers/users_helper.rb
# Helpers for User
module UsersHelper
  def dropdown_ranks
    if User.find_by(id: session[:user_id]).advisor?
      ['Guest', 'Member', 'Seargent-At-Arms', 'Reporter', 'Treasurer', 'Secretary', 'Vice President', 'President', 'Advisor']
    else
      %w(Guest Member)
    end
  end
end

app/views/admin/_admin_head.html.erb
<h1>Admin Dashboard</h1>
<ul class="nav nav-pills">
  <%= link_to 'Dashboard', admin_dashboard_path, class: 'nav-item nav-link' %>
  <%= link_to 'Teams', admin_teams_path, class: 'nav-item nav-link' %>
  <%= link_to 'Attendance', admin_attendance_path, class: 'nav-item nav-link' %>
</ul>
<hr>

app/views/admin/_attendance.html.erb
<tr>
  <%
    if params[:commit] == 'Search'
      attendance = user.attendees.where(created_at: params[:search][:from].to_date..params[:search][:to].to_date)
    else
      attendance = user.attendees
    end
  %>
  <td>
    <%= link_to user_path(user) do %>
      <%= user.name %>
    <% end %>
  </td>
  <td><%= attendance.size %></td>
  <% percent = '%.2f' % ((Float(attendance.size) / Float(@sign_up_count)) * 100) %>
  <td><%= percent == 'NaN' ? 0 : percent %>%</td>
</tr>

app/views/admin/_team.html.erb
<tr>
  <td><%= team.id %></td>
  <% event = Event.find_by_id(team.event_id) %>
  <td>
    <%= link_to event_team_path(event, team) do %>
      <%= team.name %>
    <% end %>
  </td>
  <td><%= event.name %></td>
  <td><%= format_time team.created_at %></td>
</tr>

app/views/admin/attendance.html.erb
<div class="main-div">
  <%= render 'admin_head' %>
  <h2>Search Attendance By Date</h2>
  <%= form_tag '/admin/attendance', method: :get do  %>
    <%= date_field :search, :from, class: 'form-control' %>
    <%= date_field :search, :to, class: 'form-control' %>
    <%= submit_tag 'Search', class: 'btn btn-primary btn-sm btn-block' %>
  <% end %>
    <%= link_to 'Reset', admin_attendance_path, class: 'btn btn-secondary btn-sm btn-block' %>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Number of Meetings Attended</th>
        <th>Attendance Percentage</th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: 'attendance', collection: @users.order(:name), as: :user or 'No attandances gathered.' %>
    </tbody>
  </table>
</div>

app/views/admin/dashboard.html.erb
<div class='main-div'>
  <%= render 'admin_head' %>
  <div class='row'>
    <div class='col-lg-4 col-sm-12'>
      <h4 class='title-center'>User Verification Rate</h4>
      <%= pie_chart({"Verfied Users": User.where(verified: true).count, "Unverified Users": User.where(verified: false).count}) %>
    </div>
    <div class='col-lg-4 col-sm-12'>
      <h4 class='title-center'>Total Userbase</h4>
      <h1 class='display-1 title-center'><%= User.count %></h1>
      <h4 class='title-center'>Total Number of Teams</h4>
      <h1 class='display-1 title-center'><%= Team.count %></h1>
    </div>
    <div class='col-lg-4 col-sm-12'>
      <h4 class='title-center'>Total Number of Meeting Attendees</h4>
      <h1 class='display-1 title-center'><%= Attendee.count %></h1>
    </div>
    <div class='col-xs-12'>
      <h4>Member Sign Ups</h4>
      <%= line_chart User.group_by_month(:created_at) %>
    </div>
  </div>
</div>

app/views/admin/teams.html.erb
<div class='main-div'>
  <%= render 'admin_head' %>
  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>Team Name</th>
        <th>Event</th>
        <th>Created At</th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: 'team', collection: @teams or 'No teams created.' %>
    </tbody>
  </table>
</div>

app/views/notifier/verify_email.text.erb
Your email address <%= @user.email %> has been signed up for Lakewood Ranch TSA (https://tsa.lrhsclubs.com).

If you attempted this signup, please visit the following URL to activate your account: https://tsa.lrhsclubs.com/verify_email/<%= @user.verify_token %>
If you didn't attempt this signup, you may safely ignore this email.