config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  resources :users, only: [:index, :show, :new, :create, :edit, :update] do
    put '/change_password', to: 'users#change_password'
  end

  resources :sign_up_sheets do
    resources :attendees, only: [:index, :create, :destroy]
    get '/report', to: 'sign_up_sheets#report'
  end

  get '/verify_email/:token', to: 'users#verify_email'

  resource :sessions, only: [:create, :destroy]

  resources :events do
    resources :teams do
      resources :team_members, only: [:index, :new, :edit, :create, :update, :destroy]
    end
  end

  resources :announcements

  resources :accountability_logs do
    resources :submissions, only: [:index, :new, :show, :create, :destroy]
  end

  resources :documents

  namespace :admin do
    get 'dashboard'
    get 'teams'
    get 'attendance'
  end

  get 'courses', to: 'pages#courses'

  get 'log_in', to: 'sessions#new'
  get 'register', to: 'users#new'
  get 'log_out', to: 'sessions#destroy'
end

app/models/event.rb
# Model that represents a TSA event
class Event < ActiveRecord::Base
  validates :name, presence: true
  validates :name, length: {minimum: 1, maximum: 64}
  validates :description, presence: true
  validates :description, length: {maximum: 1024}
  validates :max_members_per_team, presence: true
  validates :max_members_per_team, numericality: {greater_than: 0}

  has_many :teams
end

app/controllers/events_controller.rb
# Controller for creating TSA events
class EventsController < ApplicationController
  respond_to :html, :json

  add_breadcrumb 'Events', :events_path

  def index
    @events = Event.all
    respond_with @events
  end

  def show
    @event = Event.find_by(id: params[:id])
    if @event
      add_breadcrumb @event.name, event_path(@event)
      respond_with @event
    else
      respond_to do |format|
        format.html { not_found }
        format.json { head status: :not_found }
      end
    end
  end

  def new
    @event = Event.new
    add_breadcrumb 'New Event', new_event_path
    respond_to :html
  end

  def edit
    @event = Event.find_by(id: params[:id])
    if @event
      add_breadcrumb 'Edit ' + @event.name, new_event_path
      respond_with @event
    else
      respond_to do |format|
        format.html { not_found }
        format.json { head status: :not_found }
      end
    end
  end

  def create
    return head status: :forbidden if session[:user_id].nil?
    return head status: :forbidden unless User.find_by(id: session[:user_id]).admin?
    event = Event.new(event_parameters_create)
    if event.save
      head status: :created, location: event_path(event)
    else
      render json: {error: event.errors}, status: :bad_request
    end
  end

  def update
    event = Event.find_by(id: params[:id])
    return head status: :not_found unless event
    if session[:user_id].nil? || !User.find_by(id: session[:user_id]).admin?
      return head status: :forbidden
    end
    if event.update(event_parameters_update)
      head status: :ok
    else
      render json: {error: event.errors}, status: :bad_request
    end
  end

  def destroy
    event = Event.find_by(id: params[:id])
    return head status: :not_found unless event
    if session[:user_id].nil? || !User.find_by(id: session[:user_id]).admin?
      return head status: :forbidden
    end
    Event.destroy(event.id)
    head status: :ok
  end

  private

  def event_parameters_create
    params.require(:event).permit(:name, :description, :max_members_per_team, :image_path, :cover_path)
  end

  def event_parameters_update
    params.require(:event).permit(:name, :description, :max_members_per_team, :image_path, :cover_path)
  end
end

app/helpers/events_helper.rb
# Helper for Events
module EventsHelper
end

app/views/events/_event.html.erb
<div class="card card-max-width mr-1">
  <div class="card-block">
    <% if event.image_path.blank? %>
      <h4 class="card-title"><%= event.name %></h4>
      <p class="card-text"><%= event.description.truncate(100, separator: ' ') %></p>
      <%= link_to 'View', event_path(event), class: 'btn btn-primary event-btn' %>
    <% else %>
      <%= image_tag event.image_path, class: "img-fluid" %>
      <p class="card-title text-center"><%= event.name %></p>
    <% end %>
  </div>
  <div class="card-footer" style="background-color: white; border-top: none;">
    <%= link_to 'View', event_path(event), class: 'btn btn-primary btn-sm btn-block event-btn' %>
  </div>
</div>

app/views/events/_team.html.erb
<tr>
  <td class='team_name'><%= team.name %></td>
  <td class='team_view'><%= link_to 'View', event_team_path(Event.find_by_id(params[:id]), team), class: 'btn btn-primary' %></td>
</tr>

app/views/events/edit.html.erb
<div class="main-div">
  <h1>Edit <%= @event.name %></h1>
  <%= form_for @event, remote: true do |f| %>

    <fieldset class="form-group">
      <%= f.label :name, class: 'form-control-label' %>
      <%= f.text_field :name, class: 'form-control', placeholder: 'Event Name' %>
    </fieldset>

    <fieldset class="form-group">
      <%= f.label :description, class: 'form-control-label' %>
      <%= f.text_area :description, cols: 20, rows: 10, class: 'form-control', placeholder: 'Event Description' %>
    </fieldset>

    <fieldset class="form-group">
      <%= f.label :max_members_per_team, class: 'form-control-label' %>
      <%= f.number_field :max_members_per_team, class: 'form-control-number', max: '1000', min: '1' %>
    </fieldset>

    <fieldset class="form-group">
      <%= f.label :image_path, class: 'form-control-label' %>
      <%= f.text_field :image_path, class: 'form-control', placeholder: 'Image Path' %>
    </fieldset>

    <fieldset class="form-group">
      <%= f.label :cover_path, class: 'form-control-label' %>
      <%= f.text_field :cover_path, class: 'form-control', placeholder: 'Image Path' %>
    </fieldset>

    <%= f.submit 'Update', class: 'btn btn-primary' %>
  <% end %>
  <%= button_to 'Remove Event', { action: 'destroy', id: @event.id }, method: :delete, remote: true, class: 'btn btn-danger', data: { confirm: "Are you sure?" } %>
</div>

app/views/events/index.html.erb
<div class="cover-photo mb-1">
  <%= image_tag "trophy.jpg" %>
</div>
<div class="main-div">
  <% if logged_in %>
    <% if User.find_by_id(session[:user_id]).admin? %>
      <%= link_to new_event_path, class: 'btn btn-info float-xs-right' do %>
        <i class="fa fa-plus"></i> Create a New Event
      <% end %>
    <% end %>
  <% end %>
  <h1>All Events</h1>
  <div>
    <%= render @events %>
    <div id="spacer" style="width: 100%; height: 5rem; float:left; display:inline-block"></div>
  </div>
</div>

app/views/events/new.html.erb
<div class="main-div">
  <h1>Create a New Event</h1>

  <%= form_for @event, remote: true do |f| %>
    <fieldset class="form-group">
      <%= f.label :name, class: 'form-control-label' %>
      <%= f.text_field :name, class: 'form-control', placeholder: 'Event Name' %>
    </fieldset>

    <fieldset class="form-group">
      <%= f.label :description, class: 'form-control-label' %>
      <%= f.text_area :description, cols: 20, rows: 10, class: 'form-control', placeholder: 'Event Description' %>
    </fieldset>

    <fieldset class="form-group">
      <%= f.label :max_members_per_team, class: 'form-control-label' %>
      <%= f.number_field :max_members_per_team, class: 'form-control-number', max: '1000', min: '1' %>
    </fieldset>

    <fieldset class="form-group">
      <%= f.label :image_path, class: 'form-control-label' %>
      <%= f.text_field :image_path, class: 'form-control', placeholder: 'Image Path' %>
    </fieldset>

    <fieldset class="form-group">
      <%= f.label :cover_path, class: 'form-control-label' %>
      <%= f.text_field :cover_path, class: 'form-control', placeholder: 'Image Path' %>
    </fieldset>

    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/events/show.html.erb
<div class="cover-photo mb-1 hidden-sm-down">
  <%= image_tag @event.cover_path %>
</div>
<div class='main-div'>
    <h1 class="display-3">
      <%= @event.name %>
      <% if logged_in && current_user.admin? %>
        <% if User.find_by_id(session[:user_id]).admin? %>
          <%= link_to edit_event_path(@event), class: 'btn btn-warning btn-lg pull-right' do %>
            <i class="fa fa-cog"></i>
          <% end %>
        <% end %>
      <% end %>
    </h1>
    <p class="lead">Max Members Per Team: <%= @event.max_members_per_team %></p>
    <blockquote class="blockquote">
      <p class="m-b-0"><%= @event.description %></p>
    </blockquote>
    <hr>
    <h2 class='p-t-2'>
      Teams
      <% if logged_in %>
        <%= link_to event_teams_path(@event), class: 'btn btn-link m-b-0 pull-right' do %>
          <i class="fa fa-external-link" aria-hidden="true"></i>
        <% end %>
        <% if User.find_by_id(session[:user_id]).admin? %>
          <%= link_to new_event_team_path(@event), class: 'btn btn-info pull-right' do %>
            <i class="fa fa-plus"></i> Create a New Team
          <% end %>
        <% end %>
      <% end %>
    </h1>
    <table class="table table-striped">
      <tbody>
        <%= render partial: 'team', collection: @event.teams, as: :team or 'No teams have been created for this event.'%>
      </tbody>
    </table>
</div>